name: hexo-deploy-ftp

on:
    workflow_dispatch:
    push:
        branches:
            - master
    watch:
        types:
            - started

env:
    FTP_HOST: ${{secrets.FTP_HOST}}
    FTP_PORT: ${{secrets.FTP_PORT}}
    FTP_USERNAME: ${{secrets.FTP_USERNAME}}
    FTP_PASSWORD: ${{secrets.FTP_PASSWORD}}
    FTP_REMOTE: ${{secrets.FTP_REMOTE}}

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master

            - name: Install depends
              run: |
                  npm install

            - name: Deploy
              run: |
                  npm run deploy
