name: hexo-deploy-cos

on:
    workflow_dispatch:
    push:
        branches:
            - master

env:
    FTP_HOST: ${{secrets.FTP_HOST}}
    FTP_PORT: ${{secrets.FTP_PORT}}
    FTP_USERNAME: ${{secrets.FTP_USERNAME}}
    FTP_PASSWORD: ${{secrets.FTP_PASSWORD}}
    FTP_REMOTE: ${{secrets.FTP_REMOTE}}
    COS_SECRET_ID: ${{secrets.COS_SECRET_ID}}
    COS_SECRET_KEY: ${{secrets.COS_SECRET_KEY}}
    COS_BUCKET: ${{secrets.COS_BUCKET}}
    COS_REGION: ${{secrets.COS_REGION}}
    SITE_URL: ${{secrets.SITE_URL}}

jobs:
    build:
        runs-on: ${{ matrix.operating-system }}
        strategy:
            matrix:
                # in this example, there is a newer version already installed, 3.7.7, so the older version will be downloaded
                operating-system: ['ubuntu-latest']

        steps:
            - uses: actions/checkout@master

            - name: Install depends
              run: |
                  npm install
            - name: Build
              run: |
                  npm run build
                  
            - name: 📂 Deploy Ftp
              uses: SamKirkland/FTP-Deploy-Action@v4.3.4
              with:
                server: ${{secrets.FTP_HOST}}
                port: ${{secrets.FTP_PORT}}
                username: ${{secrets.FTP_USERNAME}}
                password: ${{ secrets.FTP_PASSWORD }}
                local-dir: './public/'
                server-dir: ${{secrets.FTP_REMOTE}}

            - name: Refresh CDN # 安装 sdk 并运行刷新脚本
              run: |
                  pip install --upgrade tencentcloud-sdk-python
                  python refresh-cdn.py -i $COS_SECRET_ID -k $COS_SECRET_KEY

            - name: Run with setup-python 3.7
              uses: actions/setup-python@v2
              with:
                  python-version: 3.7
            - name: Install dependecies
              uses: VaultVulp/action-pipenv@v2.0.1
              with:
                  command: install -d # Install all dependencies, including development ones
            - name: Update readme
              uses: VaultVulp/action-pipenv@v2.0.1
              with:
                  command: run readme

            - name: Commit and push if changed # 更新README.md
              run: |
                  git diff
                  git config --global user.email "qq88268459@126.com"
                  git config --global user.name "bmqy"
                  git add README.md
                  git commit -m "Github Action Auto Updated"
                  git push

            - name: Notify workflow status to telegram
              uses: yakuhzi/notify-workflow@v2
              if: always()
              with:
                  chat_id: ${{ secrets.TELEGRAM_TO }}
                  bot_token: ${{ secrets.TELEGRAM_TOKEN }}
                  job_status: ${{ job.status }}
