name: hexo-deploy-ftp

on:
    workflow_dispatch:
    push:
        branches:
            - master
    watch:
        types:
            - started

env:
    FTP_HOST: ${{secrets.FTP_HOST}}
    FTP_PORT: ${{secrets.FTP_PORT}}
    FTP_USERNAME: ${{secrets.FTP_USERNAME}}
    FTP_PASSWORD: ${{secrets.FTP_PASSWORD}}
    FTP_REMOTE: ${{secrets.FTP_REMOTE}}

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master

            - name: Install depends
              run: |
                  npm install

            - name: Deploy
              run: |
                  npm run deploy
            - name: Telegram Notify
              # You may pin to the exact commit or the version.
              # uses: appleboy/telegram-action@ae54341a85fdcf97cbea354678d7b8c062286c15
              uses: appleboy/telegram-action@0.0.3
              with:
                  to: ${{secrets.TELEGRAM_TO}}
                  token: ${{secrets.TELEGRAM_TOKEN}}
                  message: |
                    ${{github.actor}} created commit:
                    Commit message: ${{github.event.commits[0].message}}
                    Repository: ${{github.repository}}
                    See changes: https://github.com/${{github.repository}}/commit/${{github.sha}}
