name: hexo-deploy-cos

on:
    workflow_dispatch:
    push:
        branches:
            - master

env:
    FTP_HOST: ${{secrets.FTP_HOST}}
    FTP_PORT: ${{secrets.FTP_PORT}}
    FTP_USERNAME: ${{secrets.FTP_USERNAME}}
    FTP_PASSWORD: ${{secrets.FTP_PASSWORD}}
    FTP_REMOTE: ${{secrets.FTP_REMOTE}}
    COS_SECRET_ID: ${{secrets.COS_SECRET_ID}}
    COS_SECRET_KEY: ${{secrets.COS_SECRET_KEY}}
    COS_BUCKET: ${{secrets.COS_BUCKET}}
    COS_REGION: ${{secrets.COS_REGION}}

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master

            - name: Install depends
              run: |
                  npm install
            - name: Deploy
              run: |
                  npm run deploy

            - name: Run with setup-python 3.7.4
              uses: actions/setup-python@v2.2.2
              with:
                  python-version: 3.7.4
            - name: Install dependecies
              uses: VaultVulp/action-pipenv@v2.0.1
              with:
                  command: install -d # Install all dependencies, including development ones
            - name: Update readme
              uses: VaultVulp/action-pipenv@v2.0.1
              with:
                  command: run update_readme

            - name: Notify workflow status to telegram
              uses: yakuhzi/notify-workflow@v2
              if: always()
              with:
                  chat_id: ${{ secrets.TELEGRAM_TO }}
                  bot_token: ${{ secrets.TELEGRAM_TOKEN }}
                  job_status: ${{ job.status }}
